### ISSUE TITLE
[BUG] Debugging the Cloud Run node hello-world app doesnt work

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#261]
1) run the [CR node hello-world application](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/cloud-run-updates/nodejs/nodejs-cloud-run-hello-world) using `skaffold debug`

expected: debugging works
actual: application starts up with errors:

```
Port forwarding pod/node-local-t-5f558f75b-hbmgz in namespace default, remote port 8080 -> address 127.0.0.1 port 8081
Port forwarding pod/node-local-t-5f558f75b-hbmgz in namespace default, remote port 9229 -> address 127.0.0.1 port 9229
[node-local-t-5f558f75b-hbmgz node-local-t-container] Debugger listening on ws://127.0.0.1:9229/2cae197c-b3fa-4e05-aeeb-244df89b3205
[node-local-t-5f558f75b-hbmgz node-local-t-container] For help, see: https://nodejs.org/en/docs/inspector
[node-local-t-5f558f75b-hbmgz node-local-t-container] 
[node-local-t-5f558f75b-hbmgz node-local-t-container] > nodejs-cloud-run-hello-world@0.0.1 debug /usr/src/app
[node-local-t-5f558f75b-hbmgz node-local-t-container] > node --inspect=9229 index.js
[node-local-t-5f558f75b-hbmgz node-local-t-container] 
[node-local-t-5f558f75b-hbmgz node-local-t-container] Starting inspector on 127.0.0.1:9229 failed: address already in use
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR! code ELIFECYCLE
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR! errno 12
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR! nodejs-cloud-run-hello-world@0.0.1 debug: `node --inspect=9229 index.js`
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR! Exit status 12
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR! 
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR! Failed at the nodejs-cloud-run-hello-world@0.0.1 debug script.
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[node-local-t-5f558f75b-hbmgz node-local-t-container] 
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR! A complete log of this run can be found in:
[node-local-t-5f558f75b-hbmgz node-local-t-container] npm ERR!     /root/.npm/_logs/2020-03-31T22_50_34_271Z-debug.log
Forwarding container node-local-t-5f558f75b-hbmgz/node-local-t-container to local port 8081.
```

(note: running with `skaffold dev` works fine)

Replacing, in the [Dockerfile](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/cloud-run-updates/nodejs/nodejs-cloud-run-hello-world/Dockerfile):
`CMD ["npm", "run", "debug"]`

With (which is how our Kubernetes samples are configured):
`ENTRYPOINT ["node", "--inspect=9229", "index.js"]`

Fixes the issue

**Comment by etanshaul** [comment]
@balopat to see if this is an issue on Skaffold's side as well.

note: in order to run this app with Skaffold, you need to create k8s manifests. My testing was via the IDE's integration which generates this automatically for you. For testing, you can use (generated via `gcloud code export`):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: node-local-t
  name: node-local-t
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-local-t
  template:
    metadata:
      labels:
        app: node-local-t
    spec:
      containers:
      - env:
        - name: PORT
          value: '8080'
        - name: K_CONFIGURATION
          value: node-local-t
        - name: K_REVISION
          value: local
        - name: K_SERVICE
          value: node-local-t
        image: node-local-t
        name: node-local-t-container
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1.0
            memory: 268435456
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: node-local-t
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-local-t
  type: LoadBalancer
```
